# Generated by Django 6.0.4 on 2026-04-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_financial_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transação', 'verbose_name_plural': 'transações'},
        ),
    ]
